# Generated by Django 4.2.7 on 2025-11-24 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_products', models.JSONField(default=list, help_text='JSON array of product IDs')),
                ('followed_countries', models.JSONField(default=list, help_text='JSON array of country names')),
                ('categories', models.JSONField(default=list, help_text='JSON array of alert categories')),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('realtime', 'Realtime'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Alert Preference',
                'verbose_name_plural': 'User Alert Preferences',
            },
        ),
    ]
