# Generated by Django 4.2.7 on 2025-11-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_job_title_user_phone_number_useralertpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_balance',
            field=models.IntegerField(default=0, verbose_name='Token Balance'),
        ),
    ]
