# Generated by Django 4.2.7 on 2026-04-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAlertPreference',
        ),
    ]
