# Generated by Django 4.2.7 on 2025-11-24 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=512)),
                ('summary', models.TextField()),
                ('category', models.CharField(help_text='e.g., Price Surge, Supply Disruption', max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50)),
                ('detected_at', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(blank=True, help_text='Additional data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='companies.sector')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='e.g., Dawn, Reuters', max_length=255)),
                ('url', models.URLField(max_length=1024)),
                ('title', models.CharField(max_length=512)),
                ('full_text', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='market_intel.alert')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='market_intel.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Analysis',
                'verbose_name_plural': 'Saved Analyses',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'alert')},
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['product', 'severity'], name='market_inte_product_b8ad2e_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['detected_at'], name='market_inte_detecte_a15208_idx'),
        ),
    ]
