# Generated by Django 4.2.11 on 2026-03-19 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('query_text', models.TextField()),
                ('query_family', models.SmallIntegerField(blank=True, null=True)),
                ('parsed_intent', models.CharField(blank=True, default='', max_length=16)),
                ('parsed_product', models.CharField(blank=True, default='', max_length=256)),
                ('parsed_country', models.CharField(blank=True, default='', max_length=128)),
                ('result_count', models.IntegerField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Interaction Log',
                'verbose_name_plural': 'Search Interaction Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'query_family'], name='search_sear_created_74be26_idx')],
            },
        ),
    ]
