# Generated by Django 4.2.7 on 2026-04-20 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_redeemcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('HS_CODE', 'HS Code (Category)'), ('PRODUCT', 'Product (Subcategory)')], max_length=10)),
                ('hscode', models.CharField(db_index=True, help_text="The HS code this access applies to, e.g. '1702.3000'", max_length=20)),
                ('product_name', models.CharField(blank=True, help_text='Sub-category name when access_type=PRODUCT. Null for HS_CODE access.', max_length=255, null=True)),
                ('tokens_spent', models.IntegerField(default=0)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Access Grant',
                'verbose_name_plural': 'User Access Grants',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='useraccess',
            constraint=models.UniqueConstraint(fields=('user', 'hscode', 'product_name'), name='unique_user_access_grant'),
        ),
    ]
