# Generated by Django 4.2.7 on 2026-04-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_useraccess_useraccess_unique_user_access_grant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useraccess',
            name='unique_user_access_grant',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='product_name',
        ),
        migrations.AddField(
            model_name='useraccess',
            name='subcat_id',
            field=models.IntegerField(blank=True, help_text='Canonical ID of ProductSubCategory when access_type=PRODUCT. Null for HS_CODE access.', null=True),
        ),
        migrations.AddConstraint(
            model_name='useraccess',
            constraint=models.UniqueConstraint(fields=('user', 'hscode', 'subcat_id'), name='unique_user_access_grant'),
        ),
    ]
