# Generated by Django 4.2.7 on 2026-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_useraccess_unique_user_access_grant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='hscode',
            field=models.CharField(db_index=True, help_text="The HS code this access applies to, e.g. '1702.3000'", max_length=50),
        ),
    ]
