# Generated by Django 4.2.11 on 2026-03-15 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=500, unique=True)),
                ('entity_type', models.CharField(choices=[('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('BOTH', 'Both')], default='SELLER', max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('raw_names', models.JSONField(default=list)),
                ('shipment_count', models.IntegerField(default=0)),
                ('total_volume_mt', models.FloatField(default=0.0)),
                ('avg_price_usd_mt', models.FloatField(default=0.0)),
                ('last_shipment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canonical Entity',
                'verbose_name_plural': 'Canonical Entities',
                'ordering': ['-shipment_count'],
            },
        ),
        migrations.CreateModel(
            name='EntityMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name_a', models.CharField(max_length=500)),
                ('raw_name_b', models.CharField(max_length=500)),
                ('similarity_score', models.FloatField()),
                ('decision', models.CharField(choices=[('MATCH', 'Match — same entity'), ('NON_MATCH', 'Non-match — different entities'), ('UNCERTAIN', 'Uncertain — requires human review')], max_length=15)),
                ('method', models.CharField(default='auto', max_length=50)),
                ('reviewed_by_human', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_logs', to='entity_resolution.canonicalentity')),
            ],
            options={
                'verbose_name': 'Entity Merge Log',
                'verbose_name_plural': 'Entity Merge Logs',
            },
        ),
        migrations.AddIndex(
            model_name='canonicalentity',
            index=models.Index(fields=['canonical_name'], name='entity_reso_canonic_47dd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalentity',
            index=models.Index(fields=['entity_type'], name='entity_reso_entity__2185a6_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalentity',
            index=models.Index(fields=['country'], name='entity_reso_country_744b58_idx'),
        ),
        migrations.AddIndex(
            model_name='entitymergelog',
            index=models.Index(fields=['decision'], name='entity_reso_decisio_dcc40a_idx'),
        ),
        migrations.AddIndex(
            model_name='entitymergelog',
            index=models.Index(fields=['reviewed_by_human'], name='entity_reso_reviewe_377767_idx'),
        ),
    ]
