# Generated by Django 4.2.7 on 2025-11-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('tx_reference', models.CharField(blank=True, max_length=255)),
                ('reporting_date', models.DateField()),
                ('reporting_country', models.CharField(max_length=100)),
                ('hs_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('shipper', models.CharField(blank=True, max_length=255)),
                ('shipper_code', models.CharField(blank=True, max_length=100)),
                ('consignee', models.CharField(blank=True, max_length=255)),
                ('consignee_country', models.CharField(blank=True, max_length=100)),
                ('port_of_origin', models.CharField(blank=True, max_length=50)),
                ('port_of_entry', models.CharField(blank=True, max_length=50)),
                ('std_quantity', models.DecimalField(blank=True, decimal_places=6, help_text='Standardized quantity', max_digits=20, null=True)),
                ('std_unit', models.CharField(blank=True, help_text='e.g., MT, KG, LBS', max_length=20)),
                ('unit_rate_usd', models.DecimalField(blank=True, decimal_places=6, help_text='Price per unit in USD', max_digits=20, null=True)),
                ('fob_value_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Total FOB value in USD', max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('raw_record', models.JSONField(blank=True, help_text='Original data as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='companies.sector')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-reporting_date'],
                'indexes': [models.Index(fields=['reporting_date', 'product'], name='trade_data__reporti_f91e01_idx'), models.Index(fields=['shipper'], name='trade_data__shipper_9c5f35_idx'), models.Index(fields=['consignee_country'], name='trade_data__consign_e64c4e_idx'), models.Index(fields=['hs_code'], name='trade_data__hs_code_d23e37_idx')],
            },
        ),
        migrations.CreateModel(
            name='HsToProductMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional mapping notes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_mappings', to='companies.sector')),
            ],
            options={
                'verbose_name': 'HS to Product Map',
                'verbose_name_plural': 'HS to Product Maps',
                'ordering': ['hs_code'],
                'indexes': [models.Index(fields=['hs_code'], name='trade_data__hs_code_a84037_idx')],
            },
        ),
        migrations.CreateModel(
            name='AggProductMonthCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('total_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('avg_price_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('total_value_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_country_aggregations', to='companies.sector')),
            ],
            options={
                'verbose_name': 'Agg Product Month Country',
                'verbose_name_plural': 'Agg Product Month Country',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['product', 'year', 'month', 'country'], name='trade_data__product_96d24d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AggCompanyMonthProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('avg_price_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('total_value_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_product_aggregations', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_monthly_aggregations', to='companies.sector')),
            ],
            options={
                'verbose_name': 'Agg Company Month Product',
                'verbose_name_plural': 'Agg Company Month Product',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['company', 'product', 'year', 'month'], name='trade_data__company_bbbe1d_idx')],
            },
        ),
    ]
