# Generated by Django 4.2.7 on 2025-12-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='trade_data__reporti_f91e01_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trade_data__shipper_9c5f35_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='trade_data__consign_e64c4e_idx',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='reporting_country',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='consignee_country',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fob_value_usd',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='port_of_entry',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='port_of_origin',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='raw_record',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shipper_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='std_quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='unit_rate_usd',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='pkr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='qty_kg',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='qty_mt',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipping_agent',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='sub_category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='usd_per_kg',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='usd_per_mt',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ingested_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='std_unit',
            field=models.CharField(default='MT', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_reference',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reporting_date'], name='trade_data__reporti_a857fd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer'], name='trade_data__buyer_7bec3d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller'], name='trade_data__seller_e13850_idx'),
        ),
    ]
