# Generated by Django 4.2.7 on 2025-12-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0002_remove_transaction_trade_data__reporti_f91e01_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shipping_agent',
            field=models.CharField(max_length=500),
        ),
    ]
