# Generated by Django 4.2.7 on 2025-12-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0003_alter_transaction_buyer_alter_transaction_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sub_category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_reference',
            field=models.CharField(max_length=500),
        ),
    ]
