# Generated by Django 4.2.7 on 2025-12-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0004_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hstoproductmap',
            name='product',
        ),
        migrations.AlterField(
            model_name='hstoproductmap',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
