# Generated by Django 4.2.7 on 2025-12-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0007_alter_product_name_alter_productcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trade_type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
