# Generated by Django 4.2.7 on 2025-12-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0008_transaction_trade_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500, unique=True)),
                ('embedding', models.JSONField()),
                ('cluster_tag', models.CharField(blank=True, max_length=100)),
                ('pagerank', models.FloatField(default=0.0)),
                ('degree', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company Embedding',
                'verbose_name_plural': 'Company Embeddings',
            },
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('cluster_tag', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.productitem')),
            ],
            options={
                'verbose_name': 'Product Embedding',
                'verbose_name_plural': 'Product Embeddings',
                'unique_together': {('product_item',)},
            },
        ),
    ]
