# Generated by Django 4.2.7 on 2026-02-02 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0009_companyembedding_productembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=50)),
                ('forecast_month', models.DateField(help_text='First day of the forecasted month')),
                ('predicted_volume_mt', models.DecimalField(decimal_places=6, max_digits=20)),
                ('confidence_lower', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('confidence_upper', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('model_used', models.CharField(help_text='e.g., LightGBM, XGBoost, Ensemble', max_length=50)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('training_mape', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='trade_data.productitem')),
            ],
            options={
                'verbose_name': 'Demand Forecast',
                'verbose_name_plural': 'Demand Forecasts',
                'ordering': ['-forecast_month'],
                'indexes': [models.Index(fields=['hs_code', 'forecast_month'], name='trade_data__hs_code_989296_idx'), models.Index(fields=['forecast_month'], name='trade_data__forecas_3a9ef6_idx')],
                'unique_together': {('hs_code', 'forecast_month', 'model_used')},
            },
        ),
    ]
