# Generated by Django 4.2.7 on 2026-02-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0009_companyembedding_productembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggcompanymonthproduct',
            name='company',
        ),
        migrations.RemoveField(
            model_name='aggcompanymonthproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='aggproductmonthcountry',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='country',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_country',
            field=models.CharField(db_index=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_country',
            field=models.CharField(db_index=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qty_kg',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qty_mt',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trade_type',
            field=models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], db_index=True, default='IMPORT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['trade_type'], name='trade_data__trade_t_584967_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['origin_country'], name='trade_data__origin__9d8dad_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['destination_country'], name='trade_data__destina_dcf34b_idx'),
        ),
        migrations.DeleteModel(
            name='AggCompanyMonthProduct',
        ),
        migrations.DeleteModel(
            name='AggProductMonthCountry',
        ),
    ]
