# Generated by Django 4.2.7 on 2026-03-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0010_remove_aggcompanymonthproduct_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='hs_code',
            field=models.CharField(max_length=50),
        ),
    ]
