# Generated by Django 4.2.11 on 2026-03-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0010_remove_aggcompanymonthproduct_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProductStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=500)),
                ('entity_role', models.CharField(choices=[('SELLER', 'Seller'), ('BUYER', 'Buyer')], db_index=True, max_length=10)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('total_volume_mt', models.FloatField(default=0.0)),
                ('shipment_count', models.IntegerField(default=0)),
                ('avg_price_usd_mt', models.FloatField(default=0.0)),
                ('max_shipment_vol_mt', models.FloatField(default=0.0)),
                ('avg_shipment_vol_mt', models.FloatField(default=0.0)),
                ('first_shipment_date', models.DateField(blank=True, null=True)),
                ('last_shipment_date', models.DateField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_stats', to='trade_data.productsubcategory')),
            ],
            options={
                'verbose_name': 'Company Product Stats',
                'verbose_name_plural': 'Company Product Stats',
                'indexes': [models.Index(fields=['company_name', 'entity_role'], name='trade_data__company_0505b2_idx'), models.Index(fields=['sub_category', 'entity_role', 'country'], name='trade_data__sub_cat_01d458_idx'), models.Index(fields=['entity_role', 'country', 'total_volume_mt'], name='trade_data__entity__2f8268_idx'), models.Index(fields=['last_shipment_date'], name='trade_data__last_sh_e7b9eb_idx')],
                'unique_together': {('company_name', 'sub_category', 'entity_role')},
            },
        ),
    ]
