# Generated by Django 4.2.7 on 2026-03-17 18:59

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0011_alter_productsubcategory_hs_code'),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
    ]
