# Generated by Django 4.2.11 on 2026-03-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0011_add_company_product_stats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyproductstats',
            unique_together={('company_name', 'sub_category', 'entity_role', 'country')},
        ),
    ]
