# Generated by Django 4.2.11 on 2026-04-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0012_auto_20260317_2359'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['trade_type', 'product_item'], name='tx_type_product_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['product_item', 'trade_type', 'seller'], name='tx_prod_type_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['product_item', 'trade_type', 'buyer'], name='tx_prod_type_buyer_idx'),
        ),
    ]
