# Generated by Django 4.2.7 on 2026-01-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLensProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hs_code', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trade Lens Product',
                'verbose_name_plural': 'Trade Lens Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TradeLensTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_mt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('buyer_name', models.CharField(max_length=255)),
                ('seller_name', models.CharField(max_length=255)),
                ('buyer_country', models.CharField(max_length=100)),
                ('seller_country', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('trade_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=10)),
                ('hs_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='trade_lens.tradelensproduct')),
            ],
            options={
                'verbose_name': 'Trade Lens Transaction',
                'verbose_name_plural': 'Trade Lens Transactions',
                'ordering': ['-trade_date'],
                'indexes': [models.Index(fields=['product', 'trade_date'], name='trade_lens__product_f0be0b_idx'), models.Index(fields=['buyer_country'], name='trade_lens__buyer_c_2cd090_idx'), models.Index(fields=['seller_country'], name='trade_lens__seller__ad5b73_idx'), models.Index(fields=['port'], name='trade_lens__port_3292fa_idx'), models.Index(fields=['province'], name='trade_lens__provinc_9bcf77_idx'), models.Index(fields=['trade_type'], name='trade_lens__trade_t_beeed2_idx')],
            },
        ),
    ]
