"""
backend/training_scripts/generate_ltr_labels.py

Generates labeled (query, company_profile, relevance) triples for LTR training.

Labels are generated by:
  1. GPT-4o-mini if OPENAI_API_KEY is set in environment
  2. Heuristic judge fallback (from evaluation/generate_judgments.py) otherwise

Output: backend/training_data/ltr_labels.json
Format:
  [
    {
      "query_id": "q001",
      "query": "dextrose anhydrous suppliers from China",
      "parsed_query": {...},
      "company_name": "Shandong Pharma Co",
      "country": "China",
      "total_volume": 5000,
      "shipment_count": 12,
      "avg_price": 380,
      "last_shipment_date": "2024-03-15",
      "features": [0.12, ...],   # 15 features from FeatureExtractor
      "relevance": 3             # 0-3 label from judge
    },
    ...
  ]

Usage:
    cd backend
    python training_scripts/generate_ltr_labels.py
    python training_scripts/generate_ltr_labels.py --use-gpt --max-queries=50
"""

import os
import sys
import json
import time
import logging
import argparse
import datetime

# Add backend dir to path
BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BACKEND_DIR)

# Django setup
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'zarailink.settings')
import django
django.setup()

from search.services.query_parser import QueryInterpreter
from search.services.nlp import QueryMatcher
from search.services.aggregation import SupplierAggregator
from search.services.ranking_ltr import FeatureExtractor

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')

OUTPUT_PATH = os.path.join(BACKEND_DIR, 'training_data', 'ltr_labels.json')

# -----------------------------------------------------------------------
# Default queries (sample of golden set for label generation)
# -----------------------------------------------------------------------
SAMPLE_QUERIES = [
    # F1 — Generic discovery (original)
    "dextrose anhydrous suppliers",
    "lactose monohydrate exporters",
    "palm oil suppliers worldwide",
    "wheat flour importers",
    "white sugar suppliers",
    "sodium chloride exporters",
    "citric acid suppliers",
    "glucose syrup suppliers",

    # F2 — Country filtered (original)
    "dextrose anhydrous suppliers from China",
    "lactose monohydrate exporters from Europe",
    "palm oil from Malaysia",
    "wheat suppliers from India",
    "sugar from Brazil",

    # F3 — Volume aware (original)
    "100 MT dextrose anhydrous",
    "500 MT lactose monohydrate",
    "50 metric tons white sugar",

    # F4 — Price constrained (original)
    "dextrose under $400 per MT",
    "lactose monohydrate below $800",
    "sugar above $300 per MT",

    # F5 — Time constrained (original)
    "dextrose suppliers last 6 months",
    "recent lactose monohydrate exporters",

    # F6 — Top-K (original)
    "top 5 dextrose anhydrous suppliers",
    "best lactose exporters by volume",

    # F1 SELL intent (original)
    "who buys dextrose anhydrous",
    "buyers for lactose monohydrate",
    "which companies import palm oil",

    # ---- EXPANDED QUERIES ----

    # F1 — More generic discovery
    "sucrose suppliers",
    "fructose exporters",
    "maltodextrin suppliers",
    "sorbitol suppliers",
    "aspartame exporters",
    "caramel color suppliers",
    "starch suppliers",
    "corn starch exporters",
    "modified starch suppliers",
    "glycerol suppliers",
    "dextrin exporters",
    "trehalose suppliers",
    "mannitol exporters",
    "inositol suppliers",
    "erythritol exporters",

    # F2 — More country-filtered
    "sucrose from Thailand",
    "fructose suppliers from China",
    "maltodextrin from Germany",
    "corn starch from USA",
    "glucose from France",
    "starch from Netherlands",
    "glycerol from India",
    "dextrose from Belgium",

    # F3 — More volume-aware
    "200 MT sucrose",
    "1000 MT palm oil",
    "50 MT maltodextrin",

    # F4 — More price-constrained
    "sucrose under $500",
    "fructose below $600 per MT",
    "maltodextrin above $200",

    # F5 — More time-constrained
    "sucrose exporters last 3 months",
    "recent fructose suppliers",

    # F6 — More top-K
    "top 3 sucrose suppliers",
    "best fructose suppliers by volume",

    # SELL intent
    "buyers for sucrose",
    "who imports fructose",
    "companies buying starch",
]


# -----------------------------------------------------------------------
# Heuristic judge (no GPT needed)
# -----------------------------------------------------------------------

def _heuristic_relevance(query: str, supplier: dict, parsed_query: dict) -> int:
    """
    Score supplier relevance for query. Returns 0-3.
    3 = highly relevant, 0 = not relevant.
    """
    score = 0
    query_lower = query.lower()

    # Country filter match
    country_filter = parsed_query.get('country_filter', [])
    if country_filter:
        if supplier.get('country') in country_filter:
            score += 1
        else:
            return 0  # Country mismatch in filtered query → irrelevant

    # Volume signal
    vol = supplier.get('total_volume') or 0
    if vol > 10000:
        score += 1
    elif vol > 1000:
        score += 0

    # Recency signal
    last_date = supplier.get('last_shipment_date')
    if last_date:
        if isinstance(last_date, str):
            last_date = datetime.date.fromisoformat(last_date)
        days_ago = (datetime.date.today() - last_date).days
        if days_ago < 365:
            score += 1

    # Shipment frequency signal
    freq = supplier.get('shipment_count') or 0
    if freq >= 5:
        score += 1

    return min(score, 3)


# -----------------------------------------------------------------------
# GPT judge (optional)
# -----------------------------------------------------------------------

def _gpt_relevance(query: str, supplier: dict, client, model='gpt-4o-mini') -> int:
    prompt = (
        f"Rate the relevance of this supplier for the query on a scale of 0-3.\n\n"
        f"Query: {query}\n"
        f"Company: {supplier.get('name')} ({supplier.get('country')})\n"
        f"Volume: {supplier.get('total_volume'):.0f} MT, "
        f"Shipments: {supplier.get('shipment_count')}, "
        f"Avg price: ${supplier.get('avg_price'):.0f}/MT\n\n"
        f"0=not relevant, 1=marginally relevant, 2=relevant, 3=highly relevant\n"
        f"Return JSON: {{\"relevance\": <int>, \"reason\": \"<brief>\"}}"
    )
    for attempt in range(3):
        try:
            resp = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                max_tokens=100,
            )
            text = resp.choices[0].message.content.strip()
            data = json.loads(text)
            return int(data.get('relevance', 1))
        except Exception as e:
            if attempt == 2:
                logger.warning(f"GPT judge failed: {e}")
                return 1
            time.sleep(1)
    return 1


# -----------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------

def run(use_gpt: bool = False, max_queries: int = None):
    interpreter = QueryInterpreter()
    matcher = QueryMatcher()
    aggregator = SupplierAggregator()
    extractor = FeatureExtractor()

    # GPT client (optional)
    client = None
    if use_gpt:
        api_key = os.environ.get('OPENAI_API_KEY')
        if not api_key:
            logger.warning("OPENAI_API_KEY not set; falling back to heuristic judge")
            use_gpt = False
        else:
            from openai import OpenAI
            client = OpenAI(api_key=api_key)
            logger.info("Using GPT-4o-mini as relevance judge")

    queries = SAMPLE_QUERIES
    if max_queries:
        queries = queries[:max_queries]

    all_records = []
    total_cost_tokens = 0

    for q_idx, query in enumerate(queries):
        logger.info(f"[{q_idx+1}/{len(queries)}] Processing: {query!r}")

        parsed = interpreter.parse(query)
        product = parsed.get('product') or query

        # Get matched subcategories
        try:
            matched = matcher.match(product) if product else []
        except Exception as e:
            logger.warning(f"  Matcher error: {e}")
            continue

        if not matched:
            logger.warning(f"  No subcategory match")
            continue

        subcategory_ids = [m['id'] for m in matched[:3]]

        # Get suppliers
        try:
            suppliers = aggregator.get_suppliers_for_subcategories(
                subcategory_ids,
                intent=parsed.get('intent', 'BUY'),
                scope='WORLDWIDE',
                country_filter=parsed.get('country_filter', []),
            )
        except Exception as e:
            logger.warning(f"  Aggregation error: {e}")
            continue

        if not suppliers:
            logger.warning(f"  No suppliers found")
            continue

        for supplier in suppliers[:20]:  # up to 20 per query
            # Extract features
            try:
                features = extractor.extract(supplier, parsed)
            except Exception as e:
                logger.warning(f"  Feature extraction error: {e}")
                features = [0.0] * len(FeatureExtractor.FEATURE_NAMES)

            # Get relevance label
            if use_gpt and client:
                relevance = _gpt_relevance(query, supplier, client)
                total_cost_tokens += 200  # rough estimate
            else:
                relevance = _heuristic_relevance(query, supplier, parsed)

            record = {
                'query_id': f'q{q_idx:03d}',
                'query': query,
                'parsed_query': {k: v for k, v in parsed.items()
                                 if k not in ('sub_intents',)},
                'company_name': supplier.get('name') or supplier.get('company_name', ''),
                'country': supplier.get('country', ''),
                'total_volume': supplier.get('total_volume') or 0,
                'shipment_count': supplier.get('shipment_count') or 0,
                'avg_price': supplier.get('avg_price') or 0,
                'last_shipment_date': str(supplier.get('last_shipment_date') or ''),
                'features': [round(f, 6) for f in features],
                'feature_names': FeatureExtractor.FEATURE_NAMES,
                'relevance': relevance,
            }
            all_records.append(record)

    logger.info(f"\nGenerated {len(all_records)} labeled (query, company) pairs")
    if use_gpt:
        cost_usd = total_cost_tokens / 1_000_000 * 0.15  # GPT-4o-mini ~$0.15/1M tokens
        logger.info(f"Estimated GPT cost: ${cost_usd:.4f}")

    # Save
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, 'w') as f:
        json.dump(all_records, f, indent=2, default=str)
    logger.info(f"Saved to {OUTPUT_PATH}")
    return all_records


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate LTR training labels')
    parser.add_argument('--use-gpt', action='store_true', help='Use GPT-4o-mini as judge')
    parser.add_argument('--max-queries', type=int, default=None)
    args = parser.parse_args()
    run(use_gpt=args.use_gpt, max_queries=args.max_queries)
