# Generated by Django 4.2.7 on 2025-12-03 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hs_code', models.CharField(blank=True, help_text='Harmonized System Code', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TradeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated annual revenue in USD', max_digits=15, null=True)),
                ('trade_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Annual trade volume in USD', max_digits=15, null=True)),
                ('active_since', models.DateField(blank=True, null=True)),
                ('is_importer', models.BooleanField(default=False)),
                ('is_exporter', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_data', to='companies.company')),
            ],
            options={
                'verbose_name': 'Trade Company',
                'verbose_name_plural': 'Trade Companies',
                'ordering': ['-trade_volume'],
            },
        ),
        migrations.CreateModel(
            name='TradeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('hs_code', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('PKR', 'Pakistani Rupee'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3)),
                ('volume', models.DecimalField(decimal_places=2, help_text='Annual volume', max_digits=15)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('ton', 'Metric Ton'), ('lb', 'Pounds'), ('unit', 'Units'), ('box', 'Boxes'), ('container', 'Containers')], default='kg', max_length=20)),
                ('yoy_growth', models.DecimalField(blank=True, decimal_places=2, help_text='Year-over-year growth percentage', max_digits=6, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='trade_ledger.productcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='trade_ledger.tradecompany')),
            ],
            options={
                'verbose_name': 'Trade Product',
                'verbose_name_plural': 'Trade Products',
                'ordering': ['-volume'],
            },
        ),
        migrations.CreateModel(
            name='TradePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('port_name', models.CharField(blank=True, max_length=200)),
                ('trade_volume', models.DecimalField(decimal_places=2, help_text='Trade volume with this partner in USD', max_digits=15)),
                ('percentage_share', models.DecimalField(decimal_places=2, help_text='Percentage of total company trade', max_digits=5)),
                ('is_export', models.BooleanField(default=True, help_text='Export if True, Import if False')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='trade_ledger.tradecompany')),
            ],
            options={
                'verbose_name': 'Trade Partner',
                'verbose_name_plural': 'Trade Partners',
                'ordering': ['-trade_volume'],
            },
        ),
        migrations.CreateModel(
            name='TradeTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yoy_volume_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('yoy_price_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='trade_ledger.tradecompany')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='trade_ledger.tradeproduct')),
            ],
            options={
                'verbose_name': 'Trade Trend',
                'verbose_name_plural': 'Trade Trends',
                'ordering': ['-year', '-month'],
                'unique_together': {('company', 'product', 'month', 'year')},
            },
        ),
    ]
