# Generated by Django 4.2.7 on 2025-12-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='tradecompany',
            options={'ordering': ['-trade_volume'], 'verbose_name_plural': 'Trade Companies'},
        ),
        migrations.AlterModelOptions(
            name='tradepartner',
            options={'ordering': ['-trade_volume']},
        ),
        migrations.AlterModelOptions(
            name='tradeproduct',
            options={'ordering': ['-volume']},
        ),
        migrations.AlterModelOptions(
            name='tradetrend',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterField(
            model_name='tradecompany',
            name='estimated_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tradecompany',
            name='trade_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tradepartner',
            name='is_export',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tradepartner',
            name='percentage_share',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradepartner',
            name='trade_volume',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradeproduct',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradeproduct',
            name='yoy_growth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
