# Generated by Django 4.2.7 on 2025-11-24 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Announcement',
                'verbose_name_plural': 'Admin Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('year_established', models.IntegerField(blank=True, null=True)),
                ('number_of_employees', models.CharField(blank=True, help_text='e.g., 50-100, 100-500', max_length=50)),
                ('horeca_retail_info', models.CharField(blank=True, help_text='HORECA/retail details', max_length=255)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('premium', 'Premium')], default='unverified', max_length=50)),
                ('ntn_number', models.CharField(blank=True, help_text='National Tax Number', max_length=100)),
                ('trade_license_number', models.CharField(blank=True, max_length=100)),
                ('has_trade_data', models.BooleanField(default=False, help_text='Company appears in trade records')),
                ('is_directory_profile', models.BooleanField(default=True, help_text='Manually created vs auto-generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Company Role',
                'verbose_name_plural': 'Company Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Company Type',
                'verbose_name_plural': 'Company Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_inserted', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Error details or notes')),
            ],
            options={
                'verbose_name': 'Ingestion Log',
                'verbose_name_plural': 'Ingestion Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False, help_text='Visible without tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_contacts', to='companies.company')),
            ],
            options={
                'verbose_name': 'Key Contact',
                'verbose_name_plural': 'Key Contacts',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('product', 'Product'), ('user', 'User')], max_length=50)),
                ('entity_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('variety', models.CharField(blank=True, help_text='e.g., Basmati, Super Kernel', max_length=100)),
                ('value_added', models.CharField(blank=True, help_text='e.g., Organic certified, Pre-washed', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='companies.image')),
            ],
            options={
                'verbose_name': 'Company Product',
                'verbose_name_plural': 'Company Products',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMetricsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('metric_key', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('meta', models.JSONField(blank=True, help_text='Additional context', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_metrics', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Metrics Cache',
                'verbose_name_plural': 'Company Metrics Cache',
                'ordering': ['-metric_date'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='company_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companyrole'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companytype'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logos', to='companies.image'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.sector'),
        ),
        migrations.CreateModel(
            name='KeyContactUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('key_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='companies.keycontact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key Contact Unlock',
                'verbose_name_plural': 'Key Contact Unlocks',
                'ordering': ['-unlocked_at'],
                'indexes': [models.Index(fields=['user', 'key_contact'], name='companies_k_user_id_57c369_idx')],
                'unique_together': {('user', 'key_contact')},
            },
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['entity_type', 'entity_id'], name='companies_i_entity__9bcdc2_idx'),
        ),
        migrations.AddIndex(
            model_name='companymetricscache',
            index=models.Index(fields=['company', 'metric_key', 'metric_date'], name='companies_c_company_4ac4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['country', 'sector'], name='companies_c_country_e4d0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['verification_status'], name='companies_c_verific_2cd7c4_idx'),
        ),
    ]
