# Generated by Django 4.2.7 on 2025-12-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproduct',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='Harmonized System Nomenclature code', max_length=20),
        ),
    ]
