# Generated by Django 4.2.7 on 2025-12-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyproduct_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='market_sentiment',
            field=models.CharField(blank=True, default='Neutral', max_length=20),
        ),
    ]
