# Generated by Django 4.2.7 on 2026-03-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_market_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalCompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(db_index=True, max_length=500)),
                ('canonical_name', models.CharField(db_index=True, max_length=500)),
                ('canonical_id', models.CharField(db_index=True, max_length=100)),
                ('confidence', models.FloatField(default=1.0)),
                ('method', models.CharField(choices=[('exact', 'Exact'), ('fuzzy', 'Fuzzy EM'), ('manual', 'Manual')], default='fuzzy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canonical Company Link',
                'verbose_name_plural': 'Canonical Company Links',
                'indexes': [models.Index(fields=['canonical_id'], name='companies_c_canonic_4b22f5_idx'), models.Index(fields=['raw_name', 'canonical_name'], name='companies_c_raw_nam_1038d1_idx')],
                'unique_together': {('raw_name',)},
            },
        ),
    ]
