# Generated by Django 4.2.7 on 2026-04-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_market_sentiment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAnnouncement',
        ),
        migrations.RemoveField(
            model_name='companymetricscache',
            name='company',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='IngestionLog',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_image',
        ),
        migrations.RemoveField(
            model_name='companyproduct',
            name='image',
        ),
        migrations.DeleteModel(
            name='CompanyMetricsCache',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
